syncSecret:
  enabled: true
tenants:
- tenantId: "xxxxxxxxxxxx-f65d-4738-xxxx-xxxxxxxxxxxxxxx"
  keyVaultName: "key-vault-name"
  objects:
  - objectName: "example-secret"
    objectType: "secret"
  - objectName: "example-certificate"
    objectType: "cert" # Note: Use 'cert' for certificates
    objectAlias: "mycertificate" # Optional: Specifies a different name in Kubernetes
    objectFormat: "pem" # Optional: Specifies the format, e.g., 'pem' for certificates
logLevel: "VERBOSE"
