apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/user

components:
- ../../components/ai-shop-ingress
- ../../components/csi-secrets-store-provider-azure

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: user  # Replace this with the actual deployment name
    path: patch-user-service.yaml


